NETWORK:
  ACTIVATION: "relu"
  NORM_INPUT: false
  NB_CLASSES: 4

DATA:
  DATA_LOADER_PARAMS: { "batch_size": 100, "shuffle": True, "num_workers": 1 }
  INPUT_DIR: ""
  SPLITS_LOC: ""
  SPLIT: 0

TRAINING:
  LR: 0.0001
  EPOCHS: 42

EXPERIMENTS_DIR: ""
