# Split number of CAMUS dataset to use
SPLIT_NB: 1

# path to the CAMUS dataset in nifti format
CAMUS_DATA_LOCATION: "../local_data/database_nifti"

# path to the CAMUS dataset subgroups info defining the cross validation splits
CAMUS_SPLITS_LOCATION: "../local_data/subgroups_CAMUS"

# relative output path for where to store the preprocessed data
PREPROCESSING_OUT_LOC: "preprocessing_output/cv1"

# Which GPU to use (if available)
GPU: 0

TRAINING:
  AUGMENTATION_PARAMS: []
  MEAN: 0
  STD: 0
  NB_EPOCHS: 100
  LOSS: "DICE"
  OPTIMIZER: "Adam"
  LR: 0.001
  PATIENCE: 1000
  BATCH_SIZE: 32
  DATA_LOADER_PARAMS: { "batch_size": 32, "shuffle": True, "num_workers": 8 }
  NOTE: "With BN"

REL_OUT_DIR: "vanilla_unet1"

MODEL:
  INPUT_SHAPE: 1,256,256
  # add more model specific parameters here
