TRAIN_TXT_PATH: "/home/andekje/masters-thesis/unet1/preprocessing_output/HUNT4_data/train.txt"
VAL_TXT_PATH: "/home/andekje/masters-thesis/unet1/preprocessing_output/HUNT4_data/val.txt"

# Which GPU to use (if available)
GPU: 0

TRAINING:
  AUGMENTATION_PARAMS: []
  MEAN: 0
  STD: 0
  NB_EPOCHS: 100
  LOSS: "DICE"
  OPTIMIZER: "Adam"
  LR: 0.001
  PATIENCE: 20
  BATCH_SIZE: 32
  DATA_LOADER_PARAMS: { "batch_size": 32, "shuffle": True, "num_workers": 8 }
  NOTE: "With BN"

REL_OUT_DIR: "vanilla_unet1"

MODEL:
  INPUT_SHAPE: 1,256,256
  DEEP_SUPERVISION: True
  # add more model specific parameters here
