# Split number of CAMUS dataset to use
SPLIT_NB: 1

# path to the CAMUS dataset in nifti format
CAMUS_DATA_LOCATION: "../local_data/database_nifti"

# path to the CAMUS dataset subgroups info defining the cross validation splits
CAMUS_SPLITS_LOCATION: "../local_data/subgroups_CAMUS"

# relative output path for where to store the preprocessed data
PREPROCESSING_OUT_LOC: "preprocessing_output/cv1"

# Which GPU to use (if available)
GPU: 0

TESTING:
  AUGMENTATION_PARAMS: []
  NB_EPOCHS: 100
  LOSS: "DICE"
  OPTIMIZER: "Adam"
  LR: 0.001
  BATCH_SIZE: 32
  DATA_LOADER_PARAMS: { "batch_size": 4, "shuffle": False, "num_workers": 8 }

REL_OUT_DIR: "vanilla_unet1"

MODEL:
  INPUT_SHAPE: 1,256,256
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/baseline/model_epoch_9_dice_0.89.pth
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240221-141819/model_epoch_83_dice_0.49.pth
  PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240222-170859/model_epoch_55_dice_0.5.pth # veldig bra, men 0 LA
  PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240226-124035/model_epoch_13_dice_0.22.pth
  # add more model specific parameters here
