# Split number of CAMUS dataset to use
SPLIT_NB: 1

# path to the CAMUS dataset in nifti format
CAMUS_DATA_LOCATION: "../local_data/database_nifti"

# path to the CAMUS dataset subgroups info defining the cross validation splits
CAMUS_SPLITS_LOCATION: "../local_data/subgroups_CAMUS"

# relative output path for where to store the preprocessed data
PREPROCESSING_OUT_LOC: "preprocessing_output/cv1"

# Which GPU to use (if available)
GPU: 0

TESTING:
  AUGMENTATION_PARAMS: []
  NB_EPOCHS: 100
  LOSS: "DICE"
  OPTIMIZER: "Adam"
  LR: 0.001
  BATCH_SIZE: 32
  DATA_LOADER_PARAMS: { "batch_size": 1, "shuffle": True, "num_workers": 8 }

REL_OUT_DIR: "vanilla_unet1"

MODEL:
  INPUT_SHAPE: 1,256,256
  # PATH_TO_MODEL: ~/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240220-132907/model_epoch_100_loss_-0.9.pth
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240220-132907/model_epoch_100_loss_-0.9.pth
  PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240221-113701/model_epoch_70_loss_-0.91.pth
  # add more model specific parameters here
