TEST_TXT_PATH: "/home/andekje/masters-thesis/unet1/preprocessing_output/HUNT4_data/val.txt"

# Which GPU to use (if available)
GPU: 0

TESTING:
  AUGMENTATION_PARAMS: []
  NB_EPOCHS: 100
  LOSS: "DICE"
  OPTIMIZER: "Adam"
  LR: 0.001
  BATCH_SIZE: 32
  DATA_LOADER_PARAMS: { "batch_size": 1, "shuffle": False, "num_workers": 2 }

REL_OUT_DIR: "vanilla_unet1"

MODEL:
  INPUT_SHAPE: 1,256,256
  DEEP_SUPERVISION: False
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/baseline/model_epoch_9_dice_0.89.pth
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240221-141819/model_epoch_83_dice_0.49.pth
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240409-094320/model_epoch_76_dice_0.9.pth
  # PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240513-114044/model_epoch_10_dice_0.89.pth
  PATH_TO_MODEL: /home/andekje/masters-thesis/unet1/experiments/vanilla_unet1/20240229-104318-baseline_nobg/model_epoch_27_dice_0.88.pth
  # add more model specific parameters here
